### ISSUE TITLE
SafePad 1.3 : Find dialog not displaying a button to close

### ISSUE THREAD

**Issue by Gavin-Holt** [stephenhaunts/SafePad#1]
I tried the latest binary from github. On my windows 7 machine the find box cannot be dismissed - its window is too small. I don't have massive text or an unusual setup. This is a problem as it although it's not model it is set to always on top!

Line 66 of FindAndReplaceForm.Designer.cs set the ok button position at 363, 156
Line  159 of FindAndReplaceForm.Designer.cs sets some autoscale numbers 6F, 13F

I guess this is the cause of  my problem but I'm not a programmer so I can fix it.

Kind Regards

G
![safepad](https://user-images.githubusercontent.com/5831149/27131612-535ca6d0-5103-11e7-8632-5352f3d5efb7.jpg)

**Comment by ghost** [comment]
Do you tried **Alt+F4**?

**Comment by Gavin-Holt** [comment]
Hi

Many thanks I can work with Alt-F4.

Kind Regards Gavin Holt
